/* This file is generated by cbindgen. Do not edit by hand.
 * Regenerate with: cbindgen --config cbindgen.toml --crate cptbl --output cptbl_ffi.h
 */

#ifndef fox_cptbl_ffi_h
#define fox_cptbl_ffi_h

/* Warning: This file is autogenerated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Translate a CP-1047 (IBM EBCDIC) byte to its ISO-8859-1 equivalent.
 *
 * Equivalent to `cp1047_8859_1[c]` in the original C++ header.
 */
unsigned char fox_cptbl_cp1047_to_8859(unsigned char c);

/**
 * Return `true` when byte `c` is considered "illegal" in old ICU sources.
 *
 * Equivalent to `oldIllegal[c]` in the original C++ header.
 */
bool fox_cptbl_old_illegal(unsigned char c);

/**
 * Return a const pointer to the 256-byte CP-1047 → ISO-8859-1 table.
 *
 * The pointed-to data is `'static` and must never be freed or mutated.
 */
const unsigned char *fox_cptbl_get_cp1047_table(void);

/**
 * Return a const pointer to the 256-entry `oldIllegal` bool table.
 *
 * The pointed-to data is `'static` and must never be freed or mutated.
 */
const bool *fox_cptbl_get_old_illegal_table(void);

#endif  /* fox_cptbl_ffi_h */
