[package]
name = "firefox_jsonwriter"
version = "0.1.0"
authors = ["Firefox Developers"]
edition = "2021"
license = "MPL-2.0"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]

[dev-dependencies]
