/* This file is generated by cbindgen. Do not edit by hand.
 * Regenerate with: cbindgen --config cbindgen.toml --crate chachapoly-vectors_base --output chachapoly-vectors_base_ffi.h
 */

#ifndef fox_chachapoly_vectors_base_ffi_h
#define fox_chachapoly_vectors_base_ffi_h

/* Warning: This file is autogenerated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle used by C/C++ callers.
 *
 * cbindgen emits: `typedef struct FoxChaChaPolyVectorsBase FoxChaChaPolyVectorsBase;`
 */
typedef struct FoxChaChaPolyVectorsBase FoxChaChaPolyVectorsBase;

/**
 * Allocate a new `FoxChaChaPolyVectorsBase` on the heap and return an owning
 * pointer.
 *
 * The caller must eventually call [`fox_chachapoly_vectors_base_free`].
 * Returns null only if construction panics; OOM aborts the process.
 */
struct FoxChaChaPolyVectorsBase *fox_chachapoly_vectors_base_new(void);

/**
 * Free a `FoxChaChaPolyVectorsBase` previously returned by
 * [`fox_chachapoly_vectors_base_new`].
 *
 * Passing null is safe and has no effect.
 *
 * # Safety
 * `ptr` must be null or a pointer previously returned by
 * `fox_chachapoly_vectors_base_new` that has not yet been freed.
 */
void fox_chachapoly_vectors_base_free(struct FoxChaChaPolyVectorsBase *ptr);

/**
 * Return the number of test vectors in the collection (always 2).
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
uintptr_t fox_chachapoly_vectors_base_count(const struct FoxChaChaPolyVectorsBase *ptr);

/**
 * Return the sequential ID of the test vector at `idx`, or `u32::MAX` if
 * `idx` is out of range.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
unsigned int fox_chachapoly_vectors_base_id(const struct FoxChaChaPolyVectorsBase *ptr,
                                            uintptr_t idx);

/**
 * Return a pointer to the `plaintext` bytes of vector `idx`, or null if out
 * of range.  Valid for the lifetime of `*ptr`.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
const unsigned char *fox_chachapoly_vectors_base_plaintext(const struct FoxChaChaPolyVectorsBase *ptr,
                                                           uintptr_t idx);

/**
 * Return the byte length of the `plaintext` field of vector `idx`, or
 * `usize::MAX` if out of range.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
uintptr_t fox_chachapoly_vectors_base_plaintext_len(const struct FoxChaChaPolyVectorsBase *ptr,
                                                    uintptr_t idx);

/**
 * Return a pointer to the `aad` bytes of vector `idx`, or null if out of
 * range.  Valid for the lifetime of `*ptr`.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
const unsigned char *fox_chachapoly_vectors_base_aad(const struct FoxChaChaPolyVectorsBase *ptr,
                                                     uintptr_t idx);

/**
 * Return the byte length of the `aad` field of vector `idx`, or `usize::MAX`
 * if out of range.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
uintptr_t fox_chachapoly_vectors_base_aad_len(const struct FoxChaChaPolyVectorsBase *ptr,
                                              uintptr_t idx);

/**
 * Return a pointer to the `key` bytes of vector `idx`, or null if out of
 * range.  Valid for the lifetime of `*ptr`.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
const unsigned char *fox_chachapoly_vectors_base_key(const struct FoxChaChaPolyVectorsBase *ptr,
                                                     uintptr_t idx);

/**
 * Return the byte length of the `key` field of vector `idx`, or `usize::MAX`
 * if out of range.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
uintptr_t fox_chachapoly_vectors_base_key_len(const struct FoxChaChaPolyVectorsBase *ptr,
                                              uintptr_t idx);

/**
 * Return a pointer to the `iv` bytes of vector `idx`, or null if out of
 * range.  Valid for the lifetime of `*ptr`.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
const unsigned char *fox_chachapoly_vectors_base_iv(const struct FoxChaChaPolyVectorsBase *ptr,
                                                    uintptr_t idx);

/**
 * Return the byte length of the `iv` field of vector `idx`, or `usize::MAX`
 * if out of range.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
uintptr_t fox_chachapoly_vectors_base_iv_len(const struct FoxChaChaPolyVectorsBase *ptr,
                                             uintptr_t idx);

/**
 * Return a pointer to the `ciphertext` bytes of vector `idx`, or null if out
 * of range.  Valid for the lifetime of `*ptr`.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
const unsigned char *fox_chachapoly_vectors_base_ciphertext(const struct FoxChaChaPolyVectorsBase *ptr,
                                                            uintptr_t idx);

/**
 * Return the byte length of the `ciphertext` field of vector `idx`, or
 * `usize::MAX` if out of range.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
uintptr_t fox_chachapoly_vectors_base_ciphertext_len(const struct FoxChaChaPolyVectorsBase *ptr,
                                                     uintptr_t idx);

/**
 * Return `1` if the `invalid_tag` flag is set for vector `idx`, `0` if clear,
 * or `-1` if `idx` is out of range.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
int fox_chachapoly_vectors_base_invalid_tag(const struct FoxChaChaPolyVectorsBase *ptr,
                                            uintptr_t idx);

/**
 * Return `1` if the `invalid_iv` flag is set for vector `idx`, `0` if clear,
 * or `-1` if `idx` is out of range.
 *
 * # Safety
 * `ptr` must be non-null and valid.
 */
int fox_chachapoly_vectors_base_invalid_iv(const struct FoxChaChaPolyVectorsBase *ptr,
                                           uintptr_t idx);

#endif  /* fox_chachapoly_vectors_base_ffi_h */
