// CONTRACT: cptbl API Surface
// Location: intl/icu/source/tools/escapesrc/cptbl.h
// Source type: header-only (generated by tblgen, no .cpp companion)
//
// EXPORTED SYMBOLS:
//
// static const char cp1047_8859_1[256]
//   — Translation table mapping CP-1047 (IBM EBCDIC) byte values to
//     ISO-8859-1 (Latin-1) byte values. All 256 entries are populated.
//     Used in escapesrc.cpp via `#define cp1047_to_8859(c) cp1047_8859_1[c]`.
//
// static const bool oldIllegal[256]
//   — Boolean lookup table for codepoints U+0000..U+00FF.
//     Entry is `true` when the character is considered "illegal" in old ICU
//     source files and must be retained/escaped. Covers printable ASCII
//     (roughly 0x20–0x7E) minus a handful of excluded characters (@, \, `).
//     Entry is `false` for control characters, DEL, and all bytes >= 0x80.

#include <cassert>
#include <cstdint>
#include <cstdio>

// Pull in the table under test.  Because cptbl.h declares `static` arrays,
// each translation unit gets its own copy — this is intentional.
#include "cptbl.h"

static int failures = 0;

#define CHECK(cond, msg) \
    do { \
        if (!(cond)) { \
            fprintf(stderr, "FAIL: %s (line %d): %s\n", __func__, __LINE__, msg); \
            ++failures; \
        } \
    } while (0)

// ---------------------------------------------------------------------------
// cp1047_8859_1 — size and type
// ---------------------------------------------------------------------------
static void test_cp1047_table_size() {
    // The array must have exactly 256 entries (indices 0x00–0xFF).
    static_assert(sizeof(cp1047_8859_1) == 256,
                  "cp1047_8859_1 must be exactly 256 bytes");
}

// ---------------------------------------------------------------------------
// cp1047_8859_1 — spot-check known EBCDIC→Latin-1 mappings
//
// Reference: IBM CP-1047 code page definition.
// Selected entries verified against the table in cptbl.h.
// ---------------------------------------------------------------------------
static void test_cp1047_known_mappings() {
    // EBCDIC NUL (0x00) → Latin-1 NUL (0x00)
    CHECK((uint8_t)cp1047_8859_1[0x00] == 0x00, "NUL maps to NUL");

    // EBCDIC 0x25 → newline (0x0A)
    CHECK((uint8_t)cp1047_8859_1[0x25] == 0x0A, "EBCDIC 0x25 -> LF (0x0A)");

    // EBCDIC 0x05 → HT (0x09)
    CHECK((uint8_t)cp1047_8859_1[0x05] == 0x09, "EBCDIC 0x05 -> HT (0x09)");

    // EBCDIC space (0x40) → ASCII space (0x20)
    CHECK((uint8_t)cp1047_8859_1[0x40] == 0x20, "EBCDIC space (0x40) -> ASCII space (0x20)");

    // EBCDIC 'A' (0xC1) → ASCII 'A' (0x41)
    CHECK((uint8_t)cp1047_8859_1[0xC1] == 0x41, "EBCDIC 'A' (0xC1) -> ASCII 'A' (0x41)");

    // EBCDIC 'Z' (0xE9) → ASCII 'Z' (0x5A)
    CHECK((uint8_t)cp1047_8859_1[0xE9] == 0x5A, "EBCDIC 'Z' (0xE9) -> ASCII 'Z' (0x5A)");

    // EBCDIC 'a' (0x81) → ASCII 'a' (0x61)
    CHECK((uint8_t)cp1047_8859_1[0x81] == 0x61, "EBCDIC 'a' (0x81) -> ASCII 'a' (0x61)");

    // EBCDIC 'z' (0xA9) → ASCII 'z' (0x7A)
    CHECK((uint8_t)cp1047_8859_1[0xA9] == 0x7A, "EBCDIC 'z' (0xA9) -> ASCII 'z' (0x7A)");

    // EBCDIC '0' (0xF0) → ASCII '0' (0x30)
    CHECK((uint8_t)cp1047_8859_1[0xF0] == 0x30, "EBCDIC '0' (0xF0) -> ASCII '0' (0x30)");

    // EBCDIC '9' (0xF9) → ASCII '9' (0x39)
    CHECK((uint8_t)cp1047_8859_1[0xF9] == 0x39, "EBCDIC '9' (0xF9) -> ASCII '9' (0x39)");

    // EBCDIC '.' (0x4B) → ASCII '.' (0x2E)
    CHECK((uint8_t)cp1047_8859_1[0x4B] == 0x2E, "EBCDIC '.' (0x4B) -> ASCII '.' (0x2E)");

    // Last entry: EBCDIC 0xFF → Latin-1 0x9F
    CHECK((uint8_t)cp1047_8859_1[0xFF] == 0x9F, "EBCDIC 0xFF -> Latin-1 0x9F");
}

// ---------------------------------------------------------------------------
// cp1047_8859_1 — macro alias used in escapesrc.cpp
// ---------------------------------------------------------------------------
static void test_cp1047_macro_alias() {
#define cp1047_to_8859(c) cp1047_8859_1[(uint8_t)(c)]
    // The macro must yield the same results as direct array indexing.
    CHECK(cp1047_to_8859(0xC1) == cp1047_8859_1[0xC1], "macro == direct index for 0xC1");
    CHECK(cp1047_to_8859(0xF0) == cp1047_8859_1[0xF0], "macro == direct index for 0xF0");
#undef cp1047_to_8859
}

// ---------------------------------------------------------------------------
// oldIllegal — size and type
// ---------------------------------------------------------------------------
static void test_oldillegal_table_size() {
    static_assert(sizeof(oldIllegal) == 256 * sizeof(bool),
                  "oldIllegal must have exactly 256 bool entries");
}

// ---------------------------------------------------------------------------
// oldIllegal — control characters are NOT illegal (false)
// ---------------------------------------------------------------------------
static void test_oldillegal_control_chars_false() {
    for (int i = 0x00; i <= 0x1F; ++i) {
        if (oldIllegal[i]) {
            fprintf(stderr, "FAIL: %s: control char 0x%02X should be false\n",
                    __func__, i);
            ++failures;
        }
    }
}

// ---------------------------------------------------------------------------
// oldIllegal — DEL and high bytes are NOT illegal (false)
// ---------------------------------------------------------------------------
static void test_oldillegal_del_and_high_bytes_false() {
    CHECK(!oldIllegal[0x7F], "DEL (0x7F) should be false");
    for (int i = 0x80; i <= 0xFF; ++i) {
        if (oldIllegal[i]) {
            fprintf(stderr, "FAIL: %s: high byte 0x%02X should be false\n",
                    __func__, i);
            ++failures;
        }
    }
}

// ---------------------------------------------------------------------------
// oldIllegal — specific printable ASCII entries are true
// ---------------------------------------------------------------------------
static void test_oldillegal_printable_true() {
    // Digits 0–9
    for (int i = 0x30; i <= 0x39; ++i) {
        if (!oldIllegal[i]) {
            fprintf(stderr, "FAIL: %s: digit 0x%02X should be true\n", __func__, i);
            ++failures;
        }
    }
    // Uppercase A–Z
    for (int i = 0x41; i <= 0x5A; ++i) {
        if (!oldIllegal[i]) {
            fprintf(stderr, "FAIL: %s: uppercase 0x%02X should be true\n", __func__, i);
            ++failures;
        }
    }
    // Lowercase a–z
    for (int i = 0x61; i <= 0x7A; ++i) {
        if (!oldIllegal[i]) {
            fprintf(stderr, "FAIL: %s: lowercase 0x%02X should be true\n", __func__, i);
            ++failures;
        }
    }
    // Space (0x20)
    CHECK(oldIllegal[0x20], "space (0x20) should be true");
}

// ---------------------------------------------------------------------------
// oldIllegal — specific excluded printable characters are false
// ---------------------------------------------------------------------------
static void test_oldillegal_excluded_chars_false() {
    // '$' (0x24) — false per table
    CHECK(!oldIllegal[0x24], "'$' (0x24) should be false");
    // '@' (0x40) — false per table
    CHECK(!oldIllegal[0x40], "'@' (0x40) should be false");
    // '\\' (0x5C) — false per table
    CHECK(!oldIllegal[0x5C], "'\\\\' (0x5C) should be false");
    // '`' (0x60) — false per table
    CHECK(!oldIllegal[0x60], "'`' (0x60) should be false");
}

// ---------------------------------------------------------------------------
// oldIllegal — direct spot checks from the table
// ---------------------------------------------------------------------------
static void test_oldillegal_spot_checks() {
    // Row 0x20–0x27: ' ' '!' '"' '#' '$' '%' '&' '\''
    CHECK( oldIllegal[0x20], "0x20 ' '  true");
    CHECK( oldIllegal[0x21], "0x21 '!'  true");
    CHECK( oldIllegal[0x22], "0x22 '\"' true");
    CHECK( oldIllegal[0x23], "0x23 '#'  true");
    CHECK(!oldIllegal[0x24], "0x24 '$'  false");
    CHECK( oldIllegal[0x25], "0x25 '%'  true");
    CHECK( oldIllegal[0x26], "0x26 '&'  true");
    CHECK( oldIllegal[0x27], "0x27 '\\'' true");
    // '(' ')' '*' '+' ',' '-' '.' '/'
    CHECK( oldIllegal[0x28], "0x28 '('  true");
    CHECK( oldIllegal[0x29], "0x29 ')'  true");
    CHECK( oldIllegal[0x2A], "0x2A '*'  true");
    CHECK( oldIllegal[0x2B], "0x2B '+'  true");
    CHECK( oldIllegal[0x2C], "0x2C ','  true");
    CHECK( oldIllegal[0x2D], "0x2D '-'  true");
    CHECK( oldIllegal[0x2E], "0x2E '.'  true");
    CHECK( oldIllegal[0x2F], "0x2F '/'  true");
    // '[' (0x5B) true, '\\' (0x5C) false, ']' (0x5D) true
    CHECK( oldIllegal[0x5B], "0x5B '['  true");
    CHECK(!oldIllegal[0x5C], "0x5C '\\\\' false");
    CHECK( oldIllegal[0x5D], "0x5D ']'  true");
    // '{' (0x7B) true, '|' (0x7C) true, '}' (0x7D) true, '~' (0x7E) true
    CHECK( oldIllegal[0x7B], "0x7B '{'  true");
    CHECK( oldIllegal[0x7C], "0x7C '|'  true");
    CHECK( oldIllegal[0x7D], "0x7D '}'  true");
    CHECK( oldIllegal[0x7E], "0x7E '~'  true");
}

int main() {
    test_cp1047_table_size();
    test_cp1047_known_mappings();
    test_cp1047_macro_alias();
    test_oldillegal_table_size();
    test_oldillegal_control_chars_false();
    test_oldillegal_del_and_high_bytes_false();
    test_oldillegal_printable_true();
    test_oldillegal_excluded_chars_false();
    test_oldillegal_spot_checks();

    if (failures == 0) {
        printf("All contract tests passed.\n");
        return 0;
    } else {
        fprintf(stderr, "%d contract test(s) FAILED.\n", failures);
        return 1;
    }
}
