/* This file is generated by cbindgen. Do not edit by hand.
 * Regenerate with: cbindgen --config cbindgen.toml --crate blake2b_kat --output blake2b_kat_ffi.h
 */

#ifndef fox_blake2b_kat_ffi_h
#define fox_blake2b_kat_ffi_h

/* Warning: This file is autogenerated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque C-facing handle for [`Blake2bKat`].
 *
 * cbindgen emits: `typedef struct FoxBlake2bKat FoxBlake2bKat;`
 */
typedef struct FoxBlake2bKat FoxBlake2bKat;

/**
 * Allocate and compute a [`FoxBlake2bKat`] dataset.
 *
 * Returns a non-null owning pointer on success, null on panic.
 * The caller must free the pointer with [`fox_blake2b_kat_free`].
 */
struct FoxBlake2bKat *fox_blake2b_kat_new(void);

/**
 * Free a [`FoxBlake2bKat`] previously returned by [`fox_blake2b_kat_new`].
 *
 * Passing null is safe and has no effect. Any other invalid pointer is UB.
 *
 * # Safety
 * `ptr` must be null or a valid pointer from [`fox_blake2b_kat_new`] that has
 * not already been freed.
 */
void fox_blake2b_kat_free(struct FoxBlake2bKat *ptr);

/**
 * Return the length of `kat_key` (always 64).
 *
 * # Safety
 * `ptr` must be a valid non-null pointer from [`fox_blake2b_kat_new`].
 */
uintptr_t fox_blake2b_kat_key_len(const struct FoxBlake2bKat *ptr);

/**
 * Return a pointer to the first byte of `kat_key`.
 *
 * The returned pointer is valid for the lifetime of the [`FoxBlake2bKat`]
 * object; do not use it after [`fox_blake2b_kat_free`] is called.
 *
 * # Safety
 * `ptr` must be a valid non-null pointer from [`fox_blake2b_kat_new`].
 */
const unsigned char *fox_blake2b_kat_key_data(const struct FoxBlake2bKat *ptr);

/**
 * Return the length of `kat_data` (always 256).
 *
 * # Safety
 * `ptr` must be a valid non-null pointer from [`fox_blake2b_kat_new`].
 */
uintptr_t fox_blake2b_kat_data_len(const struct FoxBlake2bKat *ptr);

/**
 * Return a pointer to the first byte of `kat_data`.
 *
 * The returned pointer is valid for the lifetime of the [`FoxBlake2bKat`]
 * object; do not use it after [`fox_blake2b_kat_free`] is called.
 *
 * # Safety
 * `ptr` must be a valid non-null pointer from [`fox_blake2b_kat_new`].
 */
const unsigned char *fox_blake2b_kat_data_ptr(const struct FoxBlake2bKat *ptr);

/**
 * Return the number of unkeyed KAT entries (always 256).
 *
 * # Safety
 * `ptr` must be a valid non-null pointer from [`fox_blake2b_kat_new`].
 */
uintptr_t fox_blake2b_kat_unkeyed_count(const struct FoxBlake2bKat *ptr);

/**
 * Return the message length for unkeyed entry `idx` (equals `idx` for all
 * valid entries).
 *
 * Returns `-1` if `idx` is out of range.
 *
 * # Safety
 * `ptr` must be a valid non-null pointer from [`fox_blake2b_kat_new`].
 */
int fox_blake2b_kat_unkeyed_msg_len(const struct FoxBlake2bKat *ptr, uintptr_t idx);

/**
 * Return a pointer to the 64-byte unkeyed hash for entry `idx`.
 *
 * Returns null if `idx` is out of range.  The pointer is valid for the
 * lifetime of the [`FoxBlake2bKat`] object.
 *
 * # Safety
 * `ptr` must be a valid non-null pointer from [`fox_blake2b_kat_new`].
 */
const unsigned char *fox_blake2b_kat_unkeyed_hash(const struct FoxBlake2bKat *ptr, uintptr_t idx);

/**
 * Return the number of keyed KAT entries (always 256).
 *
 * # Safety
 * `ptr` must be a valid non-null pointer from [`fox_blake2b_kat_new`].
 */
uintptr_t fox_blake2b_kat_keyed_count(const struct FoxBlake2bKat *ptr);

/**
 * Return the message length for keyed entry `idx` (equals `idx` for all
 * valid entries).
 *
 * Returns `-1` if `idx` is out of range.
 *
 * # Safety
 * `ptr` must be a valid non-null pointer from [`fox_blake2b_kat_new`].
 */
int fox_blake2b_kat_keyed_msg_len(const struct FoxBlake2bKat *ptr, uintptr_t idx);

/**
 * Return a pointer to the 64-byte keyed hash for entry `idx`.
 *
 * Returns null if `idx` is out of range.  The pointer is valid for the
 * lifetime of the [`FoxBlake2bKat`] object.
 *
 * # Safety
 * `ptr` must be a valid non-null pointer from [`fox_blake2b_kat_new`].
 */
const unsigned char *fox_blake2b_kat_keyed_hash(const struct FoxBlake2bKat *ptr, uintptr_t idx);

#endif  /* fox_blake2b_kat_ffi_h */
