# Cargo dependencies for firefox_jsonwriter
# This file is appended to the shared Cargo.toml when MOZ_RUST_JSONWRITER is enabled

# firefox_jsonwriter has no external dependencies
# It uses only Rust standard library

# Add the local crate as a dependency
[dependencies.firefox_jsonwriter]
path = "local/rust/firefox_jsonwriter"
