# Cargo dependencies for firefox_tarray
# This file is appended to the main Cargo.toml when --enable-rust-tarray is used

# firefox_tarray has no external dependencies (stdlib only)
# This file is here for consistency with other ports
