[package]
name = "firefox_asciimask"
version = "0.1.0"
authors = ["Firefox Developers"]
edition = "2021"
license = "MPL-2.0"

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"

[dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
